export interface SelectFieldOption {
  label: string;
  value: string;
  description?: string;
}

export const sampleSectors = [
  {
    label: "Finance",
    value: "finance",
  },
  {
    label: "Healthcare",
    value: "healthcare",
  },
  {
    label: "Technology",
    value: "technology",
  },
  {
    label: "Real Estate",
    value: "real-estate",
  },
  {
    label: "Energy",
    value: "energy",
  },
  {
    label: "Agriculture",
    value: "agriculture",
  },
  {
    label: "Retail",
    value: "retail",
  },
  {
    label: "Manufacturing",
    value: "manufacturing",
  },
  {
    label: "Education",
    value: "education",
  },
  {
    label: "Transport and Logistics",
    value: "transport-logistics",
  },
  {
    label: "Tourism and Hospitality",
    value: "tourism-hospitality",
  },
  {
    label: "Construction",
    value: "construction",
  },
  {
    label: "Media and Entertainment",
    value: "media-entertainment",
  },
];

export const incorporationTypeOptions: SelectFieldOption[] = [
  {
    value: "sole-proprietorship",
    label: "Sole Proprietorship",
  },
  {
    value: "general-partnership",
    label: "General PartnerShip",
  },
  {
    value: "limited-liability-partnership-llp",
    label: "Limited Liability Partnership (LLP)",
  },
  {
    value: "limited-liability-company-llc",
    label: "Limited Liability Company (LLC)",
  },
  {
    value: "private-limited-company",
    label: "Private Limited Company",
  },
  {
    value: "public-limited-company",
    label: "Public Limited Company",
  },
  {
    value: "s-corporation",
    label: "S Corporation",
  },
  {
    value: "c-corporation",
    label: "C Corporation",
  },
  {
    value: "non-profit-organization",
    label: "Non-Profit Organization",
  },
];

export const yearOptions = () => {
  const years = [];
  const currentYear = new Date().getFullYear();
  const endYear = currentYear - 50;

  for (let year = currentYear; year >= endYear; year--) {
    years.push({ value: year.toString(), label: year.toString() });
  }
  return years;
};

export const years: SelectFieldOption[] = [
  { value: "none", label: "Not yet registered" },
  ...yearOptions(),
];

export const locationOptions: SelectFieldOption[] = [
  { label: "Afghanistan", value: "afghanistan" },
  {
    label: "Albania",
    value: "albania",
  },
  { label: "Algeria", value: "algeria" },
  { label: "Andorra", value: "andorra" },
  {
    label: "Angola",
    value: "angola",
  },
  { label: "Antigua and Barbuda", value: "antigua_and_barbuda" },
  {
    label: "Argentina",
    value: "argentina",
  },
  { label: "Armenia", value: "armenia" },
  { label: "Australia", value: "australia" },
  {
    label: "Austria",
    value: "austria",
  },
  { label: "Azerbaijan", value: "azerbaijan" },
  { label: "Bahamas", value: "bahamas" },
  {
    label: "Bahrain",
    value: "bahrain",
  },
  { label: "Bangladesh", value: "bangladesh" },
  { label: "Barbados", value: "barbados" },
  {
    label: "Belarus",
    value: "belarus",
  },
  { label: "Belgium", value: "belgium" },
  { label: "Belize", value: "belize" },
  {
    label: "Benin",
    value: "benin",
  },
  { label: "Bhutan", value: "bhutan" },
  { label: "Bolivia", value: "bolivia" },
  {
    label: "Bosnia and Herzegovina",
    value: "bosnia_and_herzegovina",
  },
  { label: "Botswana", value: "botswana" },
  { label: "Brazil", value: "brazil" },
  {
    label: "Brunei",
    value: "brunei",
  },
  { label: "Bulgaria", value: "bulgaria" },
  { label: "Burkina Faso", value: "burkina_faso" },
  {
    label: "Burundi",
    value: "burundi",
  },
  { label: "Cabo Verde", value: "cabo_verde" },
  { label: "Cambodia", value: "cambodia" },
  {
    label: "Cameroon",
    value: "cameroon",
  },
  { label: "Canada", value: "canada" },
  {
    label: "Central African Republic",
    value: "central_african_republic",
  },
  { label: "Chad", value: "chad" },
  { label: "Chile", value: "chile" },
  {
    label: "China",
    value: "china",
  },
  { label: "Colombia", value: "colombia" },
  {
    label: "Comoros",
    value: "comoros",
  },
  {
    label: "Congo, Democratic Republic of the",
    value: "congo_democratic_republic_of_the",
  },
  { label: "Congo, Republic of the", value: "congo_republic_of_the" },
  {
    label: "Costa Rica",
    value: "costa_rica",
  },
  { label: "Croatia", value: "croatia" },
  { label: "Cuba", value: "cuba" },
  {
    label: "Cyprus",
    value: "cyprus",
  },
  { label: "Czech Republic", value: "czech_republic" },
  { label: "Denmark", value: "denmark" },
  {
    label: "Djibouti",
    value: "djibouti",
  },
  { label: "Dominica", value: "dominica" },
  {
    label: "Dominican Republic",
    value: "dominican_republic",
  },
  { label: "Ecuador", value: "ecuador" },
  { label: "Egypt", value: "egypt" },
  {
    label: "El Salvador",
    value: "el_salvador",
  },
  { label: "Equatorial Guinea", value: "equatorial_guinea" },
  { label: "Eritrea", value: "eritrea" },
  {
    label: "Estonia",
    value: "estonia",
  },
  { label: "Eswatini", value: "eswatini" },
  { label: "Ethiopia", value: "ethiopia" },
  {
    label: "Fiji",
    value: "fiji",
  },
  { label: "Finland", value: "finland" },
  { label: "France", value: "france" },
  {
    label: "Gabon",
    value: "gabon",
  },
  { label: "Gambia", value: "gambia" },
  { label: "Georgia", value: "georgia" },
  {
    label: "Germany",
    value: "germany",
  },
  { label: "Ghana", value: "ghana" },
  { label: "Greece", value: "greece" },
  {
    label: "Grenada",
    value: "grenada",
  },
  { label: "Guatemala", value: "guatemala" },
  { label: "Guinea", value: "guinea" },
  {
    label: "Guinea-Bissau",
    value: "guinea_bissau",
  },
  { label: "Guyana", value: "guyana" },
  { label: "Haiti", value: "haiti" },
  {
    label: "Honduras",
    value: "honduras",
  },
  { label: "Hungary", value: "hungary" },
  { label: "Iceland", value: "iceland" },
  {
    label: "India",
    value: "india",
  },
  { label: "Indonesia", value: "indonesia" },
  { label: "Iran", value: "iran" },
  {
    label: "Iraq",
    value: "iraq",
  },
  { label: "Ireland", value: "ireland" },
  { label: "Israel", value: "israel" },
  {
    label: "Italy",
    value: "italy",
  },
  { label: "Jamaica", value: "jamaica" },
  { label: "Japan", value: "japan" },
  {
    label: "Jordan",
    value: "jordan",
  },
  { label: "Kazakhstan", value: "kazakhstan" },
  { label: "Kenya", value: "kenya" },
  {
    label: "Kiribati",
    value: "kiribati",
  },
  { label: "Kuwait", value: "kuwait" },
  { label: "Kyrgyzstan", value: "kyrgyzstan" },
  {
    label: "Laos",
    value: "laos",
  },
  { label: "Latvia", value: "latvia" },
  { label: "Lebanon", value: "lebanon" },
  {
    label: "Lesotho",
    value: "lesotho",
  },
  { label: "Liberia", value: "liberia" },
  { label: "Libya", value: "libya" },
  {
    label: "Liechtenstein",
    value: "liechtenstein",
  },
  { label: "Lithuania", value: "lithuania" },
  { label: "Luxembourg", value: "luxembourg" },
  {
    label: "Madagascar",
    value: "madagascar",
  },
  { label: "Malawi", value: "malawi" },
  { label: "Malaysia", value: "malaysia" },
  {
    label: "Maldives",
    value: "maldives",
  },
  { label: "Mali", value: "mali" },
  { label: "Malta", value: "malta" },
  {
    label: "Marshall Islands",
    value: "marshall_islands",
  },
  { label: "Mauritania", value: "mauritania" },
  { label: "Mauritius", value: "mauritius" },
  {
    label: "Mexico",
    value: "mexico",
  },
  { label: "Micronesia", value: "micronesia" },
  { label: "Moldova", value: "moldova" },
  {
    label: "Monaco",
    value: "monaco",
  },
  { label: "Mongolia", value: "mongolia" },
  { label: "Montenegro", value: "montenegro" },
  {
    label: "Morocco",
    value: "morocco",
  },
  { label: "Mozambique", value: "mozambique" },
  { label: "Myanmar", value: "myanmar" },
  {
    label: "Namibia",
    value: "namibia",
  },
  { label: "Nauru", value: "nauru" },
  { label: "Nepal", value: "nepal" },
  {
    label: "Netherlands",
    value: "netherlands",
  },
  { label: "New Zealand", value: "new_zealand" },
  { label: "Nicaragua", value: "nicaragua" },
  {
    label: "Niger",
    value: "niger",
  },
  { label: "Nigeria", value: "nigeria" },
  { label: "North Korea", value: "north_korea" },
  {
    label: "North Macedonia",
    value: "north_macedonia",
  },
  { label: "Norway", value: "norway" },
  { label: "Oman", value: "oman" },
  {
    label: "Pakistan",
    value: "pakistan",
  },
  { label: "Palau", value: "palau" },
  { label: "Palestine", value: "palestine" },
  {
    label: "Panama",
    value: "panama",
  },
  { label: "Papua New Guinea", value: "papua_new_guinea" },
  { label: "Paraguay", value: "paraguay" },
  {
    label: "Peru",
    value: "peru",
  },
  { label: "Philippines", value: "philippines" },
  { label: "Poland", value: "poland" },
  {
    label: "Portugal",
    value: "portugal",
  },
  { label: "Qatar", value: "qatar" },
  { label: "Romania", value: "romania" },
  {
    label: "Russia",
    value: "russia",
  },
  { label: "Rwanda", value: "rwanda" },
  {
    label: "Saint Kitts and Nevis",
    value: "saint_kitts_and_nevis",
  },
  { label: "Saint Lucia", value: "saint_lucia" },
  {
    label: "Saint Vincent and the Grenadines",
    value: "saint_vincent_and_the_grenadines",
  },
  { label: "Samoa", value: "samoa" },
  { label: "San Marino", value: "san_marino" },
  {
    label: "Sao Tome and Principe",
    value: "sao_tome_and_principe",
  },
  { label: "Saudi Arabia", value: "saudi_arabia" },
  { label: "Senegal", value: "senegal" },
  {
    label: "Serbia",
    value: "serbia",
  },
  { label: "Seychelles", value: "seychelles" },
  { label: "Sierra Leone", value: "sierra_leone" },
  {
    label: "Singapore",
    value: "singapore",
  },
  { label: "Slovakia", value: "slovakia" },
  { label: "Slovenia", value: "slovenia" },
  {
    label: "Solomon Islands",
    value: "solomon_islands",
  },
  { label: "Somalia", value: "somalia" },
  { label: "South Africa", value: "south_africa" },
  {
    label: "South Korea",
    value: "south_korea",
  },
  { label: "South Sudan", value: "south_sudan" },
  { label: "Spain", value: "spain" },
  {
    label: "Sri Lanka",
    value: "sri_lanka",
  },
  { label: "Sudan", value: "sudan" },
  { label: "Suriname", value: "suriname" },
  {
    label: "Sweden",
    value: "sweden",
  },
  { label: "Switzerland", value: "switzerland" },
  { label: "Syria", value: "syria" },
  {
    label: "Taiwan",
    value: "taiwan",
  },
  { label: "Tajikistan", value: "tajikistan" },
  { label: "Tanzania", value: "tanzania" },
  {
    label: "Thailand",
    value: "thailand",
  },
  { label: "Timor-Leste", value: "timor_leste" },
  { label: "Togo", value: "togo" },
  {
    label: "Tonga",
    value: "tonga",
  },
  { label: "Trinidad and Tobago", value: "trinidad_and_tobago" },
  { label: "Tunisia", value: "tunisia" },
  {
    label: "Turkey",
    value: "turkey",
  },
  { label: "Turkmenistan", value: "turkmenistan" },
  { label: "Tuvalu", value: "tuvalu" },
  {
    label: "Uganda",
    value: "uganda",
  },
  { label: "Ukraine", value: "ukraine" },
  {
    label: "United Arab Emirates",
    value: "united_arab_emirates",
  },
  { label: "United Kingdom", value: "united_kingdom" },
  {
    label: "United States",
    value: "united_states",
  },
  { label: "Uruguay", value: "uruguay" },
  { label: "Uzbekistan", value: "uzbekistan" },
  {
    label: "Vanuatu",
    value: "vanuatu",
  },
  { label: "Vatican City", value: "vatican_city" },
  { label: "Venezuela", value: "venezuela" },
  {
    label: "Vietnam",
    value: "vietnam",
  },
  { label: "Yemen", value: "yemen" },
  { label: "Zambia", value: "zambia" },
  { label: "Zimbabwe", value: "zimbabwe" },
];

export const ownershipTypeOptions: SelectFieldOption[] = [
  {
    value: "direct-owner",
    label: "Direct owner",
    description: "Holds shares or interest directly in the company and typically has direct rights, such as voting or dividends."
  },
  {
    value: "indirect-owner",
    label: "Indirect owner",
    description: "Benefits from ownership through another entity or intermediary, like a holding company or trust, without holding direct shares."
  }
];

export const fallbackRates = {
  EUR: 1,
  AED: 3.8526,
  AFN: 77.5567,
  ALL: 99.1042,
  AMD: 413.3993,
  ANG: 1.8778,
  AOA: 979.5969,
  ARS: 1113.9453,
  AUD: 1.6617,
  AWG: 1.8778,
  AZN: 1.785,
  BAM: 1.9558,
  BBD: 2.0981,
  BDT: 127.4703,
  BGN: 1.9558,
  BHD: 0.3944,
  BIF: 3117.3558,
  BMD: 1.049,
  BND: 1.404,
  BOB: 7.2602,
  BRL: 6.0491,
  BSD: 1.049,
  BTN: 91.4153,
  BWP: 14.4765,
  BYN: 3.3825,
  BZD: 2.0981,
  CAD: 1.5037,
  CDF: 3001.8981,
  CHF: 0.9385,
  CLP: 989.0194,
  CNY: 7.6189,
  COP: 4317.847,
  CRC: 531.4173,
  CUP: 25.1768,
  CVE: 110.265,
  CZK: 24.9375,
  DJF: 186.4349,
  DKK: 7.46,
  DOP: 65.3655,
  DZD: 141.4713,
  EGP: 53.056,
  ERN: 15.7355,
  ETB: 137.4095,
  FJD: 2.4045,
  FKP: 0.8278,
  FOK: 7.4593,
  GBP: 0.8278,
  GEL: 2.952,
  GGP: 0.8278,
  GHS: 16.2677,
  GIP: 0.8278,
  GMD: 76.1435,
  GNF: 9062.7564,
  GTQ: 8.0946,
  GYD: 219.9491,
  HKD: 8.1566,
  HNL: 26.8307,
  HRK: 7.5345,
  HTG: 137.9009,
  HUF: 399.5075,
  IDR: 17147.2262,
  ILS: 3.741,
  IMP: 0.8278,
  INR: 91.4162,
  IQD: 1379.5957,
  IRR: 44225.0555,
  ISK: 145.4574,
  JEP: 0.8278,
  JMD: 164.8591,
  JOD: 0.7438,
  JPY: 156.3828,
  KES: 135.7031,
  KGS: 91.7109,
  KHR: 4210.4545,
  KID: 1.6618,
  KMF: 491.9678,
  KRW: 1504.827,
  KWD: 0.3238,
  KYD: 0.8742,
  KZT: 526.3936,
  LAK: 22936.2532,
  LBP: 93888.2972,
  LKR: 310.1199,
  LRD: 209.2123,
  LSL: 19.3072,
  LYD: 5.1453,
  MAD: 10.4144,
  MDL: 19.564,
  MGA: 4776.7715,
  MKD: 61.5946,
  MMK: 3998.9278,
  MNT: 3670.9826,
  MOP: 8.4012,
  MRU: 42.0608,
  MUR: 48.3098,
  MVR: 16.2109,
  MWK: 1834.5092,
  MXN: 21.4299,
  MYR: 4.6457,
  MZN: 67.0497,
  NAD: 19.3072,
  NGN: 1574.6604,
  NIO: 38.6002,
  NOK: 11.6978,
  NPR: 146.2646,
  NZD: 1.8405,
  OMR: 0.4033,
  PAB: 1.049,
  PEN: 3.8613,
  PGK: 4.2789,
  PHP: 60.7939,
  PKR: 293.4621,
  PLN: 4.1385,
  PYG: 8296.1955,
  QAR: 3.8185,
  RON: 4.9772,
  RSD: 117.1987,
  RUB: 90.8003,
  RWF: 1509.1761,
  SAR: 3.9339,
  SBD: 9.0839,
  SCR: 15.1682,
  SDG: 469.8623,
  SEK: 11.1582,
  SGD: 1.4039,
  SHP: 0.8278,
  SLE: 24.0156,
  SLL: 24013.2908,
  SOS: 600.3796,
  SRD: 37.6152,
  SSP: 4615.4127,
  STN: 24.5,
  SYP: 13560.9041,
  SZL: 19.3072,
  THB: 35.4056,
  TJS: 11.5012,
  TMT: 3.674,
  TND: 3.3239,
  TOP: 2.4893,
  TRY: 38.2578,
  TTD: 7.9365,
  TVD: 1.6618,
  TWD: 34.4012,
  TZS: 2723.8684,
  UAH: 43.7059,
  UGX: 3856.6326,
  USD: 1.0491,
  UYU: 45.2394,
  UZS: 13519.584,
  VES: 67.4167,
  VND: 26805.2443,
  VUV: 128.6574,
  WST: 2.9022,
  XAF: 655.957,
  XCD: 2.8324,
  XDR: 0.7991,
  XOF: 655.957,
  XPF: 119.332,
  YER: 259.5368,
  ZAR: 19.3024,
  ZMW: 29.7187,
  ZWL: 27.8104,
};
